name: Lint and best pratices for python files

on: [push, pull_request]

jobs:
  lint-standardization:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pycodestyle flake8 pylint isort
    - name: Black - Standardization Code
      run: |
        black .
      continue-on-error: true
    - name: PyCodeStyle Standardization Code
      run: |
        pycodestyle .
      continue-on-error: true
    - name: Flake8 Standardization Code
      run: |
        flake8 .
      continue-on-error: true
    - name: Isort Standardization Code
      run: |
        isort .
      continue-on-error: true
    - name: PyLint Lint Code
      run: |
        pylint ./*/src/*.py