name: Lint and best pratices for python files

on: [push, pull_request]

jobs:
  lint-standardization:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pycodestyle flake8 pylint isort
    - name: Lint and Standardization Code
      run: |
        # check for all Best Practices on Code Style
        black .
        pycodestyle .
        flake8 .
        pylint .
        isort .