name: Lint and best pratices for python files

on: [push, pull_request]

jobs:
  lint-standardization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AlwinW/actions-lint-python@master
        with:
          root-dir-list: "src"
          packages: black pycodestyle flake8 pylint isort
          max-line-length: 88